# Generated by Django 4.1.3 on 2023-08-22 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='cateogry',
            new_name='category',
        ),
    ]
