# Generated by Django 4.1.3 on 2023-08-22 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_cateogry_products_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cateogry',
            old_name='cateogry_name',
            new_name='category_name',
        ),
    ]
