# Generated by Django 4.2.4 on 2023-09-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Pending...', max_length=200, null=True),
        ),
    ]
